services:

  postgres:
    image: postgres:16
    container_name: docuai-postgres

    environment:
      POSTGRES_DB: docuai
      POSTGRES_USER: docuai
      POSTGRES_PASSWORD: docuai_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U docuai -d docuai"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


  backend:
    build: .

    container_name: docuai-backend-compose

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://docuai:docuai_password@postgres:5432/docuai
      MLFLOW_TRACKING_URI: mlruns

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped


volumes:
  postgres_data:
